version: "3"

services:
  sprint-final:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-final-prj:latest
    ports:
      - 8998:8998
      - 8280:8280
      - 15432:5432
    volumes:
      - ${AIRFLOW_DAGS_DIR:-./src/dags}:/lessons/dags
#      - ./src/dags:/lessons/dags
      - ${DATA_DIR:-./data}:/lessons/data
      - ${TEMP_DIR:-./temp}:/lessons/temp
      - ${CERT_DIR:-./cert}:/lessons/cert
#      - "./store/metabase_plugins/vertica-jdbc-12.0.4-0.jar:/opt/metabase/plugins/vertica-jdbc-12.0.4-0.jar:ro"